---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/courses":
    get:
      summary: List all courses
      tags:
      - Courses
      responses:
        '200':
          description: success
    post:
      summary: Creates a course
      tags:
      - Courses
      parameters: []
      responses:
        '201':
          description: created
        '500':
          description: internal_server_error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                instructor_name:
                  type: string
                image:
                  type: string
              required:
              - title
              - description
              - instructor_name
              - image
  "/api/v1/courses/{id}":
    get:
      summary: Retrieves a course
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  instructor_name:
                    type: string
                  image:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - title
                - description
                - instructor_name
                - image
        '404':
          description: not_found
    delete:
      summary: Delete course by id
      tags:
      - Courses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: not_found
  "/api/v1/reservations":
    get:
      summary: List all reservations
      tags:
      - Reservations
      responses:
        '200':
          description: success
    post:
      summary: Creates a reservation
      tags:
      - Reservations
      parameters: []
      responses:
        '201':
          description: created
        '400':
          description: bad_request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                course_id:
                  type: integer
                start_date:
                  type: date
              required:
              - user_id
              - course_id
              - start_date
  "/api/v1/reservations/{id}":
    delete:
      summary: Delete reservation by id
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: not_found
  "/api/v1/users":
    get:
      summary: List all users
      tags:
      - Users
      responses:
        '200':
          description: success
  "/api/v1/signup":
    post:
      summary: Register a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
        '400':
          description: bad_request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/v1/login":
    post:
      summary: Login a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
        '500':
          description: internal_server_error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
              required:
              - username
  "/api/v1/logout":
    delete:
      summary: Logout a user
      tags:
      - Users
      parameters:
      - name: user
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: penz-classes-backend.herokuapp.com/
